--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
REM INSERTING into SCHOOLDB.ADMIN
SET DEFINE OFF;
Insert into SCHOOLDB.ADMIN (EID,USERNAME,FNAME,LNAME,PASSWORD,DOB) values ('1111','alby','Albus','Dumbledore','hogwarts',to_date('05/26/1984','MM/DD/YYYY'));
REM INSERTING into SCHOOLDB.COURSE
SET DEFINE OFF;
Insert into SCHOOLDB.COURSE (CID,TITLE,CREDITS,CLEVEL,DID,MAXSIZE,WSIZE) values ('CS401','Introduction To Computer Science','3','UG','CS','2','2');
Insert into SCHOOLDB.COURSE (CID,TITLE,CREDITS,CLEVEL,DID,MAXSIZE,WSIZE) values ('CS510','Database','3','PG','CS','5','2');
Insert into SCHOOLDB.COURSE (CID,TITLE,CREDITS,CLEVEL,DID,MAXSIZE,WSIZE) values ('CS515','Software Engineering','3','PG','CS','3','2');
Insert into SCHOOLDB.COURSE (CID,TITLE,CREDITS,CLEVEL,DID,MAXSIZE,WSIZE) values ('CS520','Internet Protocols','3','PG','CS','2','2');
Insert into SCHOOLDB.COURSE (CID,TITLE,CREDITS,CLEVEL,DID,MAXSIZE,WSIZE) values ('CS525','Independent Study',null,'PG','CS','2','0');
Insert into SCHOOLDB.COURSE (CID,TITLE,CREDITS,CLEVEL,DID,MAXSIZE,WSIZE) values ('CE420','VLSI','3','UG','ECE','4','2');
Insert into SCHOOLDB.COURSE (CID,TITLE,CREDITS,CLEVEL,DID,MAXSIZE,WSIZE) values ('CS402','Numerical Methods','3','UG','CS','2','2');
Insert into SCHOOLDB.COURSE (CID,TITLE,CREDITS,CLEVEL,DID,MAXSIZE,WSIZE) values ('CS505','Algorithms','3','PG','CS','2','2');
Insert into SCHOOLDB.COURSE (CID,TITLE,CREDITS,CLEVEL,DID,MAXSIZE,WSIZE) values ('CS521','Cloud Computing','3','PG','CS','3','2');
Insert into SCHOOLDB.COURSE (CID,TITLE,CREDITS,CLEVEL,DID,MAXSIZE,WSIZE) values ('CS530','Dev-Ops','3','PG','CS','2','2');
Insert into SCHOOLDB.COURSE (CID,TITLE,CREDITS,CLEVEL,DID,MAXSIZE,WSIZE) values ('CE421','VLSI II','3','UG','ECE','4','2');
REM INSERTING into SCHOOLDB.OFFERS
SET DEFINE OFF;
REM INSERTING into SCHOOLDB.PENDING
SET DEFINE OFF;
REM INSERTING into SCHOOLDB.PRECONDITION
SET DEFINE OFF;
REM INSERTING into SCHOOLDB.REQUIRES
SET DEFINE OFF;
REM INSERTING into SCHOOLDB.SEMESTER
SET DEFINE OFF;
REM INSERTING into SCHOOLDB.STUDENT
SET DEFINE OFF;
Insert into SCHOOLDB.STUDENT (SID,LNAME,FNAME,EMAIL,PWD,GPA,SLEVEL,BILL,DID,RESIDENCY,UNAME,DOB,CREDITS) values ('101','Potter','Harry',null,'password',null,'UG','1200','ECE','In-State','username',to_date('01/12/1990','MM/DD/YYYY'),3);
Insert into SCHOOLDB.STUDENT (SID,LNAME,FNAME,EMAIL,PWD,GPA,SLEVEL,BILL,DID,RESIDENCY,UNAME,DOB,CREDITS) values ('102','Granger','Hermione',null,'password',null,'PG','0',null,'In-State','username',to_date('04/16/1989','MM/DD/YYYY'),6);
Insert into SCHOOLDB.STUDENT (SID,LNAME,FNAME,EMAIL,PWD,GPA,SLEVEL,BILL,DID,RESIDENCY,UNAME,DOB,CREDITS) values ('103','Weasley','Ron',null,'password',null,'PG','0',null,'Out of State','username',to_date('12/19/1991','MM/DD/YYYY'),9);
Insert into SCHOOLDB.STUDENT (SID,LNAME,FNAME,EMAIL,PWD,GPA,SLEVEL,BILL,DID,RESIDENCY,UNAME,DOB,CREDITS) values ('104','Malfoy','Draco',null,'password',null,'PG','0',null,'International','username',to_date('03/21/1992','MM/DD/YYYY'),9);
REM INSERTING into SCHOOLDB.TAKES
SET DEFINE OFF;
REM INSERTING into SCHOOLDB.WAITLIST
SET DEFINE OFF;
REM INSERTING into SCHOOLDB.WAITLISTING
SET DEFINE OFF;
