--------------------------------------------------------
--  File created - Friday-March-24-2017   
--------------------------------------------------------
DROP TABLE "ADMIN" cascade constraints;
DROP TABLE "COURSE" cascade constraints;
DROP TABLE "OFFERS" cascade constraints;
DROP TABLE "PENDING" cascade constraints;
DROP TABLE "PRECONDITION" cascade constraints;
DROP TABLE "REQUIRES" cascade constraints;
DROP TABLE "SEMESTER" cascade constraints;
DROP TABLE "STUDENT" cascade constraints;
DROP TABLE "TAKES" cascade constraints;
DROP TABLE "WAITLIST" cascade constraints;
DROP TABLE "WAITLISTING" cascade constraints;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "ADMIN" 
   (	"EID" VARCHAR2(20 BYTE), 
	"FNAME" CLOB, 
	"LNAME" CLOB, 
	"SSN" NUMBER(10,0), 
	"PASSWORD" CLOB DEFAULT 123456
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" 
 LOB ("FNAME") STORE AS BASICFILE (
  TABLESPACE "SCHOOLDB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("LNAME") STORE AS BASICFILE (
  TABLESPACE "SCHOOLDB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PASSWORD") STORE AS BASICFILE (
  TABLESPACE "SCHOOLDB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "ADMIN"."PASSWORD" IS '"Password Restrictions"';
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "COURSE" 
   (	"CID" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"CREDITS" VARCHAR2(20 BYTE), 
	"CLEVEL" VARCHAR2(20 BYTE), 
	"DID" VARCHAR2(20 BYTE), 
	"MAXSIZE" VARCHAR2(20 BYTE), 
	"AVSPOT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Table OFFERS
--------------------------------------------------------

  CREATE TABLE "OFFERS" 
   (	"OFID" VARCHAR2(20 BYTE), 
	"SCHEDULE" VARCHAR2(20 BYTE), 
	"LOCATION" VARCHAR2(20 BYTE), 
	"CID" VARCHAR2(20 BYTE), 
	"SEMID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Table PENDING
--------------------------------------------------------

  CREATE TABLE "PENDING" 
   (	"PSID" VARCHAR2(20 BYTE), 
	"PCID" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Table PRECONDITION
--------------------------------------------------------

  CREATE TABLE "PRECONDITION" 
   (	"PREREQID" VARCHAR2(20 BYTE), 
	"PREREQ" VARCHAR2(20 BYTE), 
	"GPA" VARCHAR2(20 BYTE), 
	"SPPERM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;

   COMMENT ON COLUMN "PRECONDITION"."SPPERM" IS 'Special Permissions';
--------------------------------------------------------
--  DDL for Table REQUIRES
--------------------------------------------------------

  CREATE TABLE "REQUIRES" 
   (	"CID" VARCHAR2(20 BYTE), 
	"REQUIRES" BINARY_DOUBLE, 
	"PREREQID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Table SEMESTER
--------------------------------------------------------

  CREATE TABLE "SEMESTER" 
   (	"SEMID" VARCHAR2(20 BYTE), 
	"YEAR" NUMBER, 
	"DEADLINE" VARCHAR2(20 BYTE), 
	"SEMESTER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "STUDENT" 
   (	"SID" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"GPA" VARCHAR2(20 BYTE), 
	"SLEVEL" VARCHAR2(20 BYTE), 
	"MINCREDITS" VARCHAR2(20 BYTE), 
	"MAXCREDITS" VARCHAR2(20 BYTE), 
	"BILL" VARCHAR2(20 BYTE), 
	"DID" VARCHAR2(20 BYTE), 
	"BALANCE" VARCHAR2(20 BYTE), 
	"RESIDENCY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Table TAKES
--------------------------------------------------------

  CREATE TABLE "TAKES" 
   (	"SID" VARCHAR2(20 BYTE), 
	"CID" VARCHAR2(20 BYTE), 
	"GRADE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Table WAITLIST
--------------------------------------------------------

  CREATE TABLE "WAITLIST" 
   (	"WSIZE" VARCHAR2(20 BYTE), 
	"PCID" VARCHAR2(20 BYTE), 
	"CID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Table WAITLISTING
--------------------------------------------------------

  CREATE TABLE "WAITLISTING" 
   (	"PSID" VARCHAR2(20 BYTE), 
	"SID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
REM INSERTING into ADMIN
SET DEFINE OFF;
REM INSERTING into COURSE
SET DEFINE OFF;
REM INSERTING into OFFERS
SET DEFINE OFF;
REM INSERTING into PENDING
SET DEFINE OFF;
REM INSERTING into PRECONDITION
SET DEFINE OFF;
REM INSERTING into REQUIRES
SET DEFINE OFF;
REM INSERTING into SEMESTER
SET DEFINE OFF;
REM INSERTING into STUDENT
SET DEFINE OFF;
REM INSERTING into TAKES
SET DEFINE OFF;
REM INSERTING into WAITLIST
SET DEFINE OFF;
REM INSERTING into WAITLISTING
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN_PK" ON "ADMIN" ("EID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Index COURSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COURSE_PK" ON "COURSE" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Index OFFERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OFFERS_PK" ON "OFFERS" ("OFID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Index PRECONDITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRECONDITION_PK" ON "PRECONDITION" ("PREREQID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Index SEMESTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMESTER_PK" ON "SEMESTER" ("SEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT_PK" ON "STUDENT" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB" ;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("EID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB"  ENABLE;
  ALTER TABLE "ADMIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN" MODIFY ("EID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB"  ENABLE;
  ALTER TABLE "COURSE" MODIFY ("CID" NOT NULL ENABLE);
  ALTER TABLE "COURSE" MODIFY ("DID" NOT NULL ENABLE);
  ALTER TABLE "COURSE" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OFFERS
--------------------------------------------------------

  ALTER TABLE "OFFERS" ADD CONSTRAINT "OFFERS_PK" PRIMARY KEY ("OFID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB"  ENABLE;
  ALTER TABLE "OFFERS" MODIFY ("OFID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRECONDITION
--------------------------------------------------------

  ALTER TABLE "PRECONDITION" ADD CONSTRAINT "PRECONDITION_PK" PRIMARY KEY ("PREREQID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB"  ENABLE;
  ALTER TABLE "PRECONDITION" MODIFY ("PREREQID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEMESTER
--------------------------------------------------------

  ALTER TABLE "SEMESTER" ADD CONSTRAINT "SEMESTER_PK" PRIMARY KEY ("SEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB"  ENABLE;
  ALTER TABLE "SEMESTER" MODIFY ("SEMID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLDB"  ENABLE;
  ALTER TABLE "STUDENT" MODIFY ("SID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAKES
--------------------------------------------------------

  ALTER TABLE "TAKES" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "TAKES" MODIFY ("CID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OFFERS
--------------------------------------------------------

  ALTER TABLE "OFFERS" ADD CONSTRAINT "OFFERS_FK1" FOREIGN KEY ("CID")
	  REFERENCES "COURSE" ("CID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "OFFERS" ADD CONSTRAINT "OFFERS_FK2" FOREIGN KEY ("SEMID")
	  REFERENCES "SEMESTER" ("SEMID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUIRES
--------------------------------------------------------

  ALTER TABLE "REQUIRES" ADD CONSTRAINT "REQUIRES_FK1" FOREIGN KEY ("CID")
	  REFERENCES "COURSE" ("CID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "REQUIRES" ADD CONSTRAINT "REQUIRES_FK2" FOREIGN KEY ("PREREQID")
	  REFERENCES "PRECONDITION" ("PREREQID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAKES
--------------------------------------------------------

  ALTER TABLE "TAKES" ADD CONSTRAINT "TAKES_FK1" FOREIGN KEY ("CID")
	  REFERENCES "COURSE" ("CID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TAKES" ADD CONSTRAINT "TAKES_FK2" FOREIGN KEY ("SID")
	  REFERENCES "STUDENT" ("SID") ON DELETE CASCADE ENABLE;
